### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#11]
Hello! I am aware about WASM support in modern Qt. It it possible to use QtRestClient and QtJsonSerializer in WASM application (originally desktop application based on Qt Widgets)?

**Comment by Skycoder42** [comment]
Generally speaking: Yes, they do support WASM in the sense that they can be successfully built. However, I have not yet tested them extensively.

**Comment by arietto** [comment]
Ok. Thanks!
