### ISSUE TITLE
Using this as a vendored dependency

### ISSUE THREAD

**Issue by ohmree** [Skycoder42/QtRestClient#13]
Hi, I'd like to make a qt-based library and I'll be using [xmake](https://xmake.io/) as my build tool of choice (xmake projects can depend on cmake-based libraries).

When building with qmake it seems like all the cmake stuff is created in a layout that's suitable for installing globally (e.g. to `/usr/{lib,include,share,bin}`), but I'd much rather vendor my dependencies as git submodules and build them alongside my own code.

Is there a way I can achieve something like that? I don't mind depending on qmake and whatever else to compile, as long as I get a directory I can use with cmake's `add_subdirectory` (well, the xmake equivalent since it can consume cmake dependencies).

Using qmake for my code isn't an option because at some point I'll need to use libraries that only support cmake, and installing globally just feels icky so I'd much rather not have to do that either.

**Comment by Skycoder42** [comment]
qmake generates various files and other "magic stuff" when building for the module to work. I am not aware of a way to include it directly. I guess, you would just have to play around with qmake and cmake (or xmake) and see whats possible...

**Comment by ohmree** [comment]
> qmake generates various files and other "magic stuff" when building for the module to work.

Could you elaborate on this? (you absolutely don't have to, telling me to learn qmake and go rtfm is also a suitable response).

Also somewhat related - [I've managed to to build QtJsonSerializer using xmake](https://github.com/ohmree/QtJsonSerializer) with only a slight rearrangement - I yanked the source code one directory up (so it all resides in `src/`) and changed the `"QtJsonSerializer/foo.h"` includes to only say `"foo.h"` (couldn't figure out how to get xmake to play nicely otherwise).
From what I understand that library only optionally uses a python script at build time to generate type registration boilerplate, which I'm not interested in anyway since it seems to add a few mb to the binary size.
Does QtRestClient do something more complex than QtJsonSerializer?

Lastly - how much of the aforementioned "magic stuff" is still relevant when not building the tool that generates REST boilerplate from xml (yuck)? I've noticed some qbs stuff going on there and that's been deprecated for a few years now.

**Comment by ohmree** [comment]
By the way, instead of vendoring dependencies as git submodules I went with a dependency management style xmake uses that involves a repo with all of my xmake recipes for whatever libraries I need (currently only QtJsonSerializer), so I can just say "use packages from my personal repo" and then "this target requires package `qtjsonserializer`" and it automagically works.
But this issue is still relevant because eventually I'd like to consume QtRestClient as a dependency in an xmake-based project.

**Comment by Skycoder42** [comment]
Well, if you managed to to it for the json serializer, the process for the rest client should be mostly the same. Most of the "magic" qmake does is to generate public headers for Qt style imports and generate various build system files (qmake, cmake, automake, ...) it basically transforms the library into what is needed for it to be imported as qt module.

I think, the only difference to QtJsonSerializer is the dependency on that. See [src/restclient/restclient.pro#L7](https://github.com/Skycoder42/QtRestClient/blob/master/src/restclient/restclient.pro#L7). If you remove the two lines and replace them by a "normal" library import (Set `INCLUDEPATH` and `LIBS`), it should work.

**Comment by ohmree** [comment]
> Most of the "magic" qmake does is to generate public headers for Qt style imports

So it just renames the headers that are placed in `build/include/`? If so, could you give an example of what it might look like?
And why not just name the headers in the project source according to the public header conventions?

**Comment by Skycoder42** [comment]
Back then, I decided to create Qt modules and followed the Qt guidelines on how to do that. This includes creating headers next to the sources, and as part of the Qt modules build, they are then "copied" to the includes directory. This also creates new headers for each class in each header and thus spares you from managing those yourself.

If you need the headers, run qmake once and check them in with your fork. Or you could download one of the binary artifacts from the [Releases Page](https://github.com/Skycoder42/QtRestClient/releases/tag/3.0.0-4) and copy them from there

**Comment by ohmree** [comment]
Well, after a good few hours and a few attempts at building this with xmake and getting xmake to play nicely with the qmake-generated cmake files I gave up and installed everything system-wide (using PKGBUILDs of course, I'm not a savage), and then it's trivial to just `add_requires("cmake::Qt5RestClient")` from xmake.
I'll close this because I don't think there's another way to achieve this that doesn't involve a big build system rewrite.
