### ISSUE TITLE
error: no matching function for call to ‘qHash(const std::optional<QString>&)’

### ISSUE THREAD

**Issue by ohmree** [Skycoder42/QtRestClient#14]
QtJsonSerializer's readme says it's supposed to work with `std::optional`, yet a bit of sample code won't compile.

[Here's my code](https://github.com/ohmree/stfu), it also has the pkgbuilds I use (since the ones on the AUR are out of date and aren't configured to my liking) and a dockerfile for non-arch users because I'm only familiar with the arch way of doing things.

The build system auto generates `foo.cpp`, `foo.h` and `moc_foo.cpp` from `src/api/foo.xml` using `qrestbuilder`, those files can be found at `build/.gens/stfu/linux/x86_64/debug/rules/restbuilder/` after running `xmake` (or `xmake -v` to see more info).

If I change the `email` property in `src/api/user.xml` from `std::optional<QString>` to just a `QString` it compiles just fine, am I doing something wrong?

I've tried sticking a `Q_DECLARE_METATYPE(std::optional<QString>)` in a few places and still got the same compilation error but I suspect this might be the key to solving this error.

**Comment by Skycoder42** [comment]
Could you post your compiler error here? Maybe then I can help

**Comment by Skycoder42** [comment]
Closed due to inactivity
