### ISSUE TITLE
Building minimalistic version

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#2]
Hello! How can I build via qmake a minimalistic version of this framework?
I mean ignoring qrestbuilder, because it required qpmx.
It will be nice if QtJsonSerializer become optional in QtRestClient too.

**Comment by Skycoder42** [comment]
There is no minimal build config yet, but it's a good idea.

To exclude qrestbuilder, simply delete the `tools` directory.

To build without the serializer, you could probably just delete all files in the library that require it and uncomment the lines in the other files that make use of those. The files to be removed would (most likely) be:
- genericrestreply.h
- paging.h
- paging_fwd.h
- metacomponent.h
- restreplyawaitable.*
- simple.h

Also remove them from the pro file. For the other files, just remove/modify the parts of the code that require it. If you have questions about those parts, feel free to ask.

**Comment by arietto** [comment]
OK, thanks.

**Comment by Skycoder42** [comment]
With the 2.2.1 release, you can now build the module without QtJsonSerializer and without qdep (which replaces qpmx from this release on). See [Building without QtJsonSerializer/qdep
](https://github.com/Skycoder42/QtRestClient#building-without-qtjsonserializerqdep) for instructions on how to do so
