### ISSUE TITLE
Ignoring response body

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#3]
Hello! I send POST queries and REST server sends empty body in response. I'd like not to treat empty body as a JSON parse error in some cases. What workaround can be used? If I meet in onAllErrors() JSON error (checking `type` variable value), then should I treat it as `onSucceeded`? Or is there any hint for REST client not to parse body as JSON? op_start_params is a `Q_GADGET` POD.

    auto rest_reply = resources_rest_class->post("start", op_start_params);
    rest_reply->onSucceeded([&](int, QObject*) {			
    //TODO
    });		
    rest_reply->onAllErrors([&](QString error, int code, QtRestClient::RestReply::ErrorType type) {
    //TODO		
    });

Should I use non-generic `callJson` method instead? But I'd like to avoid typing hardcoded HTTP verbs (as string literals).

**Comment by Skycoder42** [comment]
Currently, there is no such feature in the library. But I think this should definitely possible, so I will add something to take care of this in the future.

For now however, you should indeed use `onAllErrors` and check for a `QJsonParseError::ParseError::IllegalValue` json parse error. See [RestReplyPrivate::replyFinished](https://github.com/Skycoder42/QtRestClient/blob/master/src/restclient/restreply.cpp#L279) for more details on how the JSON parsing is done. Using `callJson` would not work, as the parsing is performed independently of the serialization, i.e. this fails already in the JSON stage. The corresponding code to handle this exception would be:

```
rest_reply->onAllErrors([&](QString error, int code, QtRestClient::RestReply::ErrorType type) {
    if (type == QtRestClient::RestReply::JsonParseError && code == QJsonParseError::IllegalValue)
        // treat as onSuccess(200, {})
    else
        // continue "normal" error handling
});
```

For the future, I think an empty response should always be allowed in the JSON `RestReply`, without any extra flags (And thus `GenericRestReply<void>` would work out of the box as well). However, for all the other `GenericRestReply<...>`, I think this should still be considered an error, unless a specific flag is set in the `RestClient`, i.e. something like a `RestClient::allowEmptyBody` property. Would you agree with this idea, or do you have other ideas/requirements to such a feature?

**Comment by arietto** [comment]
Yes, I have to use the same workaround code. 
I think QtRestClient::RestClass should have non-generalized methods like `post` which return `RestReply` with allowed empty response. Generalized methods should not be modified (if we expect JSON response, then we expect possibility of some JSON errors).
