### ISSUE TITLE
Retrieving server host within reply handler

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#4]
Hello! I'd like to receive remote host in onSucceeded/onAllErrors handlers like this: `current_rest_reply->networkReply()->request().url().host();`
How can I track `QtRestClient::RestReply` instances for multiple parallel requests?

**Comment by Skycoder42** [comment]
Well, you already showed how to get the url. The only thing you need to do now is to track the reply. There are countless ways of doing this, but 2 come to mind immediatly, depending on whether you are using the library in a function or signal/slot like style.

Functional:
```
auto reply = // some code that returns the reply...
reply->onSucceeded(this, [reply](int code, QJsonObject result){
    auto host = reply->networkReply()->request().url().host();
    // ...
});
```

Signal/slots:
```
auto reply = // some code that returns the reply...
connect(reply, &QtRestClient::RestReply::succeeded,
        this, &MyClass::someMethod);

// ...

void MyClass::someMethod(int code, QJsonValue result) {
    auto reply = qobject_cast<QtRestClient::RestReply*>(sender());
    Q_ASSERT(reply);
    auto host = reply->networkReply()->request().url().host();
    // ...
});
```

I hope this answers your question. If not, please elaborate the problem

**Comment by Skycoder42** [comment]
Can I assume this problem has been solved for you? If yes, I will close the issue

**Comment by arietto** [comment]
Sorry, thanks.
