### ISSUE TITLE
Using with CMake project

### ISSUE THREAD

**Issue by nickfromXXII** [Skycoder42/QtRestClient#5]
Is it possible to use this library with CMake project?

**Comment by Skycoder42** [comment]
Yes it is, just like any other official Qt module. When compiling the library, the required cmake files are automatically generated. They are also included in the releases and the online installer.

To use the module, just treat it like you would any other Qt module (like QtCore, QtWidgets, etc.). It works exactly the same

**Comment by nickfromXXII** [comment]
Thanks!
