### ISSUE TITLE
Setting user timeout

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#8]
Hello! I'd like to add upper timeout value for awaitable reply (out-of-the-box). For example, there is some internal system timeout. So, final_timeout = min(user_timeout, system_timeout).

**Comment by Skycoder42** [comment]
Sorry, but this is not possible. I only wrap signals with the awaitable. If you need this feature, write your own awaitable class that handles this as you need

**Comment by arietto** [comment]
Never mind! Thanks.
