### ISSUE TITLE
Disable restclientauth 

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtRestClient#9]
Hello! I have to support Qt 5.12, but modern versions of QtRestClient are incompatible with it due to restclientauth (I can't use older QtRestClient, because I need QtJsonSerializer 4.x). How can I disable restclientauth building without *.pro files modification?
restclientauth build fails because [`prepareRequest`](https://doc.qt.io/qt-5/qabstractoauth.html#prepareRequest) appeared in Qt 5.13.

**Comment by Skycoder42** [comment]
Nothing really... The project expects this. If you don't want to modify by hand, write a script that appends `SUBDIRS - = restclientauth` to src.pro

**Comment by arietto** [comment]
OK, thank you!
